package com.dbsrcnn.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import java.sql.Blob;

import javax.xml.bind.annotation.*;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Image Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "Image")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "DunamisRest/com/dunamis/lms/domain", name = "Image")
public class Convert implements Serializable {
    private static final long serialVersionUID = 1L;

    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    
    @Column(name = "imageTitle")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String imageTitle;
    
    @Column(name = "fileName")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String fileName;  
    
    @Column(name = "fileType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String fileType;
    
    @Column(name = "fileSize")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer fileSize;   
    
    @Column(name = "defaultImage")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean defaultImage; 
    
   

	public Boolean getDefaultImage() {
		return defaultImage;
	}

	public void setDefaultImage(Boolean defaultImage) {
		this.defaultImage = defaultImage;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public Integer getFileSize() {
		return fileSize;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}
	
	

	
	public String getImageTitle() {
		return imageTitle;
	}

	public void setImageTitle(String imageTitle) {
		this.imageTitle = imageTitle;
	}

	public Convert() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof Convert))
            return false;
        Convert equalCheck = (Convert) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

	

}
