package com.todo.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Status Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "Status")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "DunamisRest/com/dunamis/pPM/domain", name = "Status")
public class Status implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "Status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;
    
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="nextId", insertable = true, updatable = true, nullable = true)
    private Status next;
    
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="previousId", insertable = true, updatable = true, nullable = true)
    private Status previous;

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Status getNext() {
        return next;
    }
    
    public void setNext(Status next) {
        this.next = next;
    }
    
    public Status getPrevious() {
        return previous;
    }
    
    public void setPrevious(Status previous) {
        this.previous = previous;
    }



    public Status () {
    
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof Status))
            return false;
        Status equalCheck = (Status) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}