package com.todo.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * Book Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "Todo")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "DunamisRest/com/dunamis/lawbooks/domain", name = "Book")
public class Todo implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "title")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String title;

    @Column(name = "description", columnDefinition = "LONGTEXT")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String description;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public String getTitle() {
        return title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    
    
    @ManyToOne
    @JoinColumn(name="status")
    private Status status;
    
    
    public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}


     

	@ManyToOne
    @JoinColumn(name="person")
    private Person person;
    
    
    public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Todo() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }




	@Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof Todo))
            return false;
        Todo equalCheck = (Todo) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}